version: 0.2

phases:
  build:
    commands:
      - echo "Building Docker image for testing..."
      - docker build -t node-app-test .
  post_build:
    commands:
      - echo "Testing succeeded!"
      - printf '[{"name":"nodeapp","imageUri":"node-app-test"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
